const titles={dashboard:'Dashboard',master:'Menu Master',add:'Add New Dish',carousel:'Carousel Manager',screens:'Screen Manager',features:'Features & Rules'};
const SHEETS={id:'1GTRoGkk0LvorgMhXi4d0cddFQ0-96VxBmJ9pOuN4od8',master:'Menu_Master',images:'Image Ticker',functions:'Functions'};
let menuRows=[],imageRows=[],functionRows=[];
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===id));document.getElementById('pageTitle').textContent=titles[id]||'Menu CMS';window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
document.querySelectorAll('.go-add').forEach(b=>b.addEventListener('click',()=>showPage('add')));
document.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.target)));
document.querySelectorAll('.toggle').forEach(t=>t.addEventListener('click',()=>t.classList.toggle('on')));
document.getElementById('analyze')?.addEventListener('click',()=>{const n=document.getElementById('notice');n.textContent='Read adapter is active and verified in the UI. Write operations remain intentionally locked for the next controlled phase.';n.style.borderColor='#b9cdbd';n.style.background='#eef5ef';n.style.color='#496b55';});
function clean(v){return v==null?'':String(v).trim()}function truthy(v){return ['true','yes','1','on','active'].includes(clean(v).toLowerCase())}
function rowsFrom(table){if(!table||!table.cols)return[];const headers=table.cols.map((c,i)=>clean(c.label)||clean(c.id)||`Column_${i+1}`);return(table.rows||[]).map(r=>{const o={};headers.forEach((h,i)=>{const c=r.c&&r.c[i];o[h]=c?(c.f??c.v??''):''});return o})}
function loadSheet(key,sheet,callback){const old=document.getElementById(key);if(old)old.remove();const s=document.createElement('script');s.id=key;s.src=`https://docs.google.com/spreadsheets/d/${SHEETS.id}/gviz/tq?sheet=${encodeURIComponent(sheet)}&tqx=responseHandler:${callback}&tq=${encodeURIComponent('select *')}&headers=1&_=${Date.now()}`;s.onerror=()=>setSync('Connection error',false);document.body.appendChild(s)}
function val(row,names){for(const n of names){if(Object.prototype.hasOwnProperty.call(row,n)&&clean(row[n]))return row[n]}return''}
function setSync(text,ok=true){const box=document.querySelector('.sync');if(!box)return;box.querySelector('b').textContent=text;box.querySelector('span').textContent=ok?'Live read-only connection':'Check TEST Sheets access';box.querySelector('i').style.background=ok?'#70a67f':'#b85b52'}
function renderMenu(){const active=menuRows.filter(r=>truthy(val(r,['Active','active']))).length;const stat=document.querySelector('#dashboard .stats article:first-child');if(stat){stat.querySelector('strong').textContent=menuRows.length;stat.querySelector('small').textContent=`${active} active in TEST`}
 const table=document.querySelector('#master .table');if(table){const head=table.querySelector('.th').outerHTML;const body=menuRows.map((r,i)=>{const name=clean(val(r,['Name','Item_Name','Dish','Menu_Item']))||'Unnamed item';const id=clean(val(r,['ID','Menu_ID','Dish_ID']))||`ROW-${i+1}`;const screen=clean(val(r,['Screen','screen']))||'—';const section=clean(val(r,['Section','Category','category']))||'—';const order=clean(val(r,['Order','Sort_Order','order']))||'—';const isActive=truthy(val(r,['Active','active']));return `<div class="tr data-row"><span><b>${esc(name)}</b><small>${esc(clean(val(r,['Category','Description'])))}</small></span><span>${esc(id)}</span><span>${esc(screen)}</span><span>${esc(section)}</span><span>${esc(order)}</span><span class="${isActive?'status-on':'status-off'}">${isActive?'Active':'Inactive'}</span></div>`}).join('');table.innerHTML=head+(body||'<div class="table-empty">No Menu_Master records found.</div>')}
 const empty=document.querySelector('#dashboard .empty');if(empty){const sample=menuRows.slice(0,5).map(r=>`<button class="quick-item" data-target="master"><b>${esc(clean(val(r,['Name','Item_Name','Dish']))||'Menu item')}</b><span>${esc(clean(val(r,['Category','Screen']))||'TEST Menu_Master')}</span></button>`).join('');empty.innerHTML=sample||'<b>No menu records returned.</b><span>Check Menu_Master publishing permissions.</span>';empty.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>showPage('master')))}}
function renderImages(){const active=imageRows.filter(r=>truthy(val(r,['Active','active']))).length;const stat=document.querySelector('#dashboard .stats article:nth-child(3)');if(stat){stat.querySelector('strong').textContent=imageRows.length;stat.querySelector('small').textContent=`${active} active carousel images`}}
function esc(v){return clean(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.cmsMenuCallback=resp=>{if(resp&&resp.table){menuRows=rowsFrom(resp.table);renderMenu();setSync('TEST Sheets')}};
window.cmsImagesCallback=resp=>{if(resp&&resp.table){imageRows=rowsFrom(resp.table);renderImages()}};
window.cmsFunctionsCallback=resp=>{if(resp&&resp.table)functionRows=rowsFrom(resp.table)};
function loadTestData(){setSync('Syncing…');loadSheet('cms-master',SHEETS.master,'cmsMenuCallback');loadSheet('cms-images',SHEETS.images,'cmsImagesCallback');loadSheet('cms-functions',SHEETS.functions,'cmsFunctionsCallback')}
const search=document.querySelector('#master .toolbar .search input');search?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#master .data-row').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'grid':'none')});
loadTestData();